from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('offers/', views.offers, name='offers'),
    path('login/', views.login, name='login'),
    path('about/', views.about, name='about'),
    path('root/', views.root, name='root'),
    path('users/', views.users, name='users'),
    path('comments/', views.comments, name='comments'),
    path('routes/', views.routes, name='routes'),
    path('selectbus/', views.selectbus, name='selectbus'),
    path('ticket/', views.ticket, name='ticket'),
    path('businsert/', views.businsert, name='businsert'),
    path('comment/', views.comment, name='comment'),
    path('worker/', views.worker, name='worker'),
    path('route/', views.route, name='route'),
    path('city/', views.city, name='city'),
    path('admins/', views.admins, name='admins'),
    path('ad/', views.ad, name='ad'),
    path('get_user/', views.get_user, name='get_user'),
    path('get_route/', views.get_route, name='get_route'),
    path('ticketinfo/', views.ticketinfo, name='ticketinfo'),
    path('selectbus/', views.selectbus, name='selectbus'),
    path('book/', views.book, name='book'),
    path('Select/', views.Select, name='Select'),
    path('details/', views.details, name='details'),
    path('admindelete/', views.admindelete, name='admindelete'),
    path('delete/', views.delete, name='delete'),
    path('routedelete/', views.routedelete, name='routedelete'),
    path('workerdelete/', views.workerdelete, name='workerdelete'),
    path('busdelete/', views.busdelete, name='busdelete'),
    path('deletebus/', views.deletebus, name='deletebus'),
    path('citydelete/', views.citydelete, name='citydelete'),
    path('commentdelete/', views.commentdelete, name='commentdelete'),
    path('updatebus/', views.updatebus, name='updatebus'),
    path('changebus/', views.changebus, name='changebus'),
    path('changebuses/', views.changebuses, name='changebuses'),

]
